server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blogapp
    username: aravind
    password: Arav@1998
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
