server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blogapp
    username: aravind
    password: Arav@1998
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
